# Makefile for simple Python program
build:
	echo "nothing to build"
run:
	python3 Kobra.py < positives.txt


# alternatively:
# python tool.py < positives.txt
# if your program reads from the standard input (stdin)
